### ISSUE TITLE
Firefox support

### ISSUE THREAD

**Issue by Jak2k** [beatonma/microformats-reader#5]

**Comment by beatonma** [comment]
Hey, thanks for the request.

I started a rewrite of this extension last year which has cross-platform support [planned](https://github.com/beatonma/microformats-reader/tree/dev/app/ts/compat/browser).

I'm afraid I ended up moving on to other stuff and have not completed the rewrite but I'll try and get it back to it as soon as possible - good to know there are still people who might use it!

**Comment by Jak2k** [comment]
I found the extension in the add-on store: https://addons.mozilla.org/en-US/firefox/addon/microformats-reader/ It looks like you published it there, so I'll close this issue as done.

**Comment by beatonma** [comment]
Great! I was waiting for it to get through the approval process before saying anything about it. It just went live this afternoon and you beat me to it!

**Comment by da4089** [comment]
Thanks for this!
